apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
  - name: client-port
    port: 2181
  - name: peer-port
    port: 2888
  - name: leader-election-port
    port: 3888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: zookeeper:3.6.2
        ports:
        - containerPort: 2181
          name: client-port
        - containerPort: 2888
          name: peer-port
        - containerPort: 3888
        volumeMounts:
        - name: datadir
          mountPath: /data
      volumes:
      - name: datadir
        emptyDir: {}
