apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos-consumer
spec:
  selector:
    matchLabels:
      app: consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: localhost:5001/consumer:1.0.0
          ports:
            - containerPort: 18080